### ISSUE TITLE
Trending video per country

### ISSUE THREAD

**Issue by VivianoRiccardo** [demon071/Tiktok-API-Python#1]
Would be useful adding a feature that lets the user select the country for the trending videos as well as the number of trending videos. Anyway best Tik tok api so far, i'm surprised of 0 stars. Really.

**Comment by demon071** [comment]
I will update soon

**Comment by VivianoRiccardo** [comment]
Nice, thank you

**Comment by VivianoRiccardo** [comment]
i ve made a pull request for trending videos: https://github.com/demon071/Tiktok-API-Python/pull/4
