### ISSUE TITLE
No Longer Woking

### ISSUE THREAD

**Issue by stefanodvx** [demon071/Tiktok-API-Python#10]
https://toolav.herokuapp.com/id/?video_id= endpoint is no longer working, now it will give you status_code 1 everytime and no video data, like this you cant get the aweme_id :(

**Comment by demon071** [comment]
it's working https://toolav.herokuapp.com/id/?video_id=6926546688416976129

**Comment by frozenpandaman** [comment]
@demon071 toolav.herokuapp.com seems to be down again.

**Comment by demon071** [comment]
> @demon071 toolav.herokuapp.com seems to be down again.

I'm using the free plan so when the time limit is exceeded it will stop working, it will work again next month

**Comment by demon071** [comment]
> @demon071 toolav.herokuapp.com seems to be down again.

The new server is now available: tool-av.herokuapp.com
