### ISSUE TITLE
Last 27 items download limit

### ISSUE THREAD

**Issue by amani135** [demon071/Tiktok-API-Python#12]
Hi, thank you for your work. I'm a bit noob here, but when I try to download a user feed, it only downloads the last 27 videos. Is this normal behaviour?

**Comment by demon071** [comment]
I think the problem is in heroku's IP, when heroku server requests to tikotk, server IP will be limited to a certain range

**Comment by demon071** [comment]
> Hi, thank you for your work. I'm a bit noob here, but when I try to download a user feed, it only downloads the last 27 videos. Is this normal behaviour?

```python
import requests

video_id = '6801895105885195526' # Video ID
r = requests.session()
r.headers.update({
# Your device ID
'device_id': '6975849720443749894', 
'iid': '6975849768589444870', 
'openudid': '70ae1de46d56fdb2',

# Your proxy
"proxy-host": "",
"proxy-port": "",
"proxy-user": "",
"proxy-pass": "",
 })
url = 'http://toolav.herokuapp.com/id/?video_id={}'.format(video_id)
y = r.get(url)
print(y.text)
```

use your device ID to get data

**Comment by Khaled-BH** [comment]
https://tool-av.herokuapp.com/

https://toolav.herokuapp.com/

Can I have the source of these api ?

**Comment by demon071** [comment]
> https://tool-av.herokuapp.com/
> 
> https://toolav.herokuapp.com/
> 
> Can I have the source of these api ?

You can buy source

**Comment by Khaled-BH** [comment]
> > https://tool-av.herokuapp.com/
> > https://toolav.herokuapp.com/
> > Can I have the source of these api ?
> 
> You can buy source

How much

**Comment by demon071** [comment]
> > > https://tool-av.herokuapp.com/
> > > https://toolav.herokuapp.com/
> > > Can I have the source of these api ?
> > 
> > 
> > You can buy source
> 
> How much

150$

**Comment by Khaled-BH** [comment]
> > > > https://tool-av.herokuapp.com/
> > > > https://toolav.herokuapp.com/
> > > > Can I have the source of these api ?
> > > 
> > > 
> > > You can buy source
> > 
> > 
> > How much
> 
> 150$

Can I have your email please ?

**Comment by demon071** [comment]
> > > > > https://tool-av.herokuapp.com/
> > > > > https://toolav.herokuapp.com/
> > > > > Can I have the source of these api ?
> > > > 
> > > > 
> > > > You can buy source
> > > 
> > > 
> > > How much
> > 
> > 
> > 150$
> 
> Can I have your email please ?

Telegram: t.me/demon071
