### ISSUE TITLE
Server source code

### ISSUE THREAD

**Issue by 89z** [demon071/Tiktok-API-Python#14]
where is the source code for this server:

https://toolav.herokuapp.com/id/?video_id=7038589018707070213

**Comment by hos2020** [comment]
yes we need it

**Comment by demon071** [comment]
this is one of the functions of server heroku

**Comment by demon071** [comment]
> yes we need it

full source 250$

**Comment by 89z** [comment]
Dont need it anymore :)

http://api2.musical.ly/aweme/v1/aweme/detail/?aweme_id=7038589018707070213

**Comment by demon071** [comment]
> Dont need it anymore :)
> 
> http://api2.musical.ly/aweme/v1/aweme/detail/?aweme_id=7038589018707070213

does it work for user feed
