### ISSUE TITLE
how to get video count for music id?

### ISSUE THREAD

**Issue by lazezo2** [demon071/Tiktok-API-Python#16]
thanks for the great work
using"getMusicFeed" i can get videos from music id for specific count (must be multiply of 30)
how to get video count for music id?
i mean how many videos found in music id

**Comment by demon071** [comment]
number of videos in music ID unknown, but maximum less than 1000 videos

**Comment by lazezo2** [comment]
thanks for quick reply,
i hope to add that in future
thanks

**Comment by demon071** [comment]
ok i will check and update
