### ISSUE TITLE
cannot unpack non-iterable bool object

### ISSUE THREAD

**Issue by lazezo2** [demon071/Tiktok-API-Python#17]
getUserFeed  not working any more
using getUserFeed example get that error
TypeError: cannot unpack non-iterable bool object

**Comment by demon071** [comment]
Bug fixed

**Comment by lazezo2** [comment]
yes now it work, however there  is another problem
if the user id is not English for example french (have accent) it will not work...
for example: user id "julméré"
any idea?

**Comment by demon071** [comment]
you can send me link tiktok user

**Comment by lazezo2** [comment]
> you can send me link tiktok user

example user id is "julméré" so the link should be like that
https://www.tiktok.com/@julméré
however this link is not valid! and by search i found the working user link
https://www.tiktok.com/@MS4wLjABAAAAZjjeyobMEXLT9jVMWG9Su8ZuGVLWONB-VlbV1oyjwVFrz8RwRMR37ze_GlyO7ROR

i checked that new link and user id is the same and found that tiktok used secUid instead of user id in case of french name!!!
user id is "julméré"
secUid  is "MS4wLjABAAAAZjjeyobMEXLT9jVMWG9Su8ZuGVLWONB-VlbV1oyjwVFrz8RwRMR37ze_GlyO7ROR"
however using userid or secUid  in getUserFeed example not working.....

**Comment by demon071** [comment]
Updated, you can you use  Api.getUserFeed(user_url='https://www.tiktok.com/@MS4wLjABAAAAZjjeyobMEXLT9jVMWG9Su8ZuGVLWONB-VlbV1oyjwVFrz8RwRMR37ze_GlyO7ROR')

**Comment by lazezo2** [comment]
it's working very well, thanks alot
