### ISSUE TITLE
getInfoVideo cannot unpack non-iterable bool object

### ISSUE THREAD

**Issue by lazezo2** [demon071/Tiktok-API-Python#19]
try to get tiktok info by tiktok video url

`
from TiktokApi import *
Api = Tiktok()
limit = 1000
count = 0
setFlag = 0
max_cursor = 0
url="https://www.tiktok.com/@whyao11141/video/7066723377112747290"
#
by_url, cookie = Api.getInfoVideo(url=url)
dl = Download(cookie=cookie, path='video')
print (by_url)
  
`

but i got this error

> 

Traceback (most recent call last):
  File "/content/TiktokApi/api.py", line 263, in getInfoVideo
    return json.loads(resp)['props']['pageProps'], res.cookies.get_dict()
KeyError: 'props'

---------------------------------------------------------------------------

TypeError                                 Traceback (most recent call last)

<ipython-input-14-3c0294e0f2af> in <module>()
     10 #
     11 error_count=0
---> 12 userFeed, cookie = Api.getInfoVideo(url=url)
     13 dl = Download(cookie=cookie, path='video')
     14 print (userFeed)

TypeError: cannot unpack non-iterable bool object

any idea?

**Comment by demon071** [comment]
fixed the error

**Comment by lazezo2** [comment]
Thanks, problem solved
