### ISSUE TITLE
getInfoUser() stopped working

### ISSUE THREAD

**Issue by bumsun** [demon071/Tiktok-API-Python#21]
Request doesn't receive a response.

**Comment by demon071** [comment]
Please check your IP, when restricted by tiktok the response is very slow

**Comment by bumsun** [comment]
IP isn't restricted. Selenium requests are working.

**Comment by demon071** [comment]
ok, i will update the selenium option

**Comment by demon071** [comment]
> IP isn't restricted. Selenium requests are working.
update:
use info = Api.getInfoUser(username='tiktok', use_selenium=True) to use selenium
