### ISSUE TITLE
getChallengeFeed minCursor, maxCursor, count

### ISSUE THREAD

**Issue by Khimer** [demon071/Tiktok-API-Python#23]
Hello! Can you explain what the selection of "minCursor", "maxCursor", "count" values in the getChallengeFeed method is based on? With the values "minCursor"==0 and "maxCursor"==0, I get a list of videos by the tag I need. And also at the end of the server response there is ""...hasMore":true,"maxCursor":"128805","minCursor":"2157990","itemABParams":[],"webToken":""},"errMsg ":null}". However, with the subsequent "minCursor"==0 and "maxCursor"==30, there are no videos by the tag, although there are much more of them on the site.
Thanks!

**Comment by demon071** [comment]
maybe tiktok changed the API
