### ISSUE TITLE
cannot unpack non-iterable bool object

### ISSUE THREAD

**Issue by lazezo2** [demon071/Tiktok-API-Python#24]
api stop working and show this error

`[]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/TiktokApi/api.py", line 92, in getUserFeed
    resp = res.json()
  File "/usr/local/lib/python3.7/dist-packages/requests/models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] <!DOCTYPE html><html lang="en" pc="yes">

        # i removed the html code because hes is big!!!!!
</html>

TypeError                                 Traceback (most recent call last)

[<ipython-input-10-5ce2e653f5f1>](https://localhost:8080/#) in <module>()
     41 
     42 while True:
---> 43     userFeed, cookie = Api.getUserFeed(username=user_name, max_cursor=max_cursor)
     44     dl = Download(cookie=cookie, path=folder1)
     45     for post in userFeed['itemListData']:

TypeError: cannot unpack non-iterable bool object`

  # i removed the html code from the error report because he is big!!!!!
this error happen with getMusicFeed and with getUserFeed

**Comment by demon071** [comment]
tiktok changed the API so currently the APIs are not working, I will update the API

**Comment by lazezo2** [comment]
thanks for your concern, waiting for update

**Comment by demon071** [comment]
updated
