### ISSUE TITLE
No module named 'TiktokApi.browser'

### ISSUE THREAD

**Issue by lazezo2** [demon071/Tiktok-API-Python#26]
thanks for the update, i already test it but didn't work so thought it's still under progress....
using any example like user feed example  
this error happen

`ModuleNotFoundError                       Traceback (most recent call last)

[<ipython-input-6-58958e18ec8d>](https://localhost:8080/#) in <module>()
----> 1 from TiktokApi import *
      2 
      3 Api = Tiktok()
      4 
      5 # nhập tên người dùng

1 frames

[/content/TiktokApi/api.py](https://localhost:8080/#) in <module>()
      8 import pickle
      9 from urllib.parse import urlencode, quote
---> 10 from .browser import Browser
     11 from .ultis import set_url, get_param_url
     12 from .encryption import get_tt_param

ModuleNotFoundError: No module named 'TiktokApi.browser'`

i am using google colab, any help will be appreciated

**Comment by demon071** [comment]
> thanks for the update, i already test it but didn't work so thought it's still under progress.... using any example like user feed example this error happen
> 
> `ModuleNotFoundError Traceback (most recent call last)
> 
> in () ----> 1 from TiktokApi import * 2 3 Api = Tiktok() 4 5 # nhập tên người dùng
> 
> 1 frames
> 
> [/content/TiktokApi/api.py](https://localhost:8080/#) in () 8 import pickle 9 from urllib.parse import urlencode, quote ---> 10 from .browser import Browser 11 from .ultis import set_url, get_param_url 12 from .encryption import get_tt_param
> 
> ModuleNotFoundError: No module named 'TiktokApi.browser'`
> 
> i am using google colab, any help will be appreciated

you need all the modules for it to work, I've only tested it on Windows

**Comment by lazezo2** [comment]
is there any work around to make it work in google colab?
may be using chromium instead of browser or passing tiktok cookies manually to tiktok-api?

`# install chromium, its driver, and selenium
!apt-get update
!apt install chromium-chromedriver
!cp /usr/lib/chromium-browser/chromedriver /usr/bin
!pip install selenium
# set options to be headless, ..
from selenium import webdriver
options = webdriver.ChromeOptions()
options.add_argument('--headless')
options.add_argument('--no-sandbox')
options.add_argument('--disable-dev-shm-usage')
# open it, go to a website, and get results
wd = webdriver.Chrome('chromedriver',options=options)
wd.get("https://www.website.com")
print(wd.page_source)  # results`

**Comment by demon071** [comment]
for it to work on Colab i think need to use requests and some method of getting datapost encoding

**Comment by lazezo2** [comment]
can you give me an example?

**Comment by lazezo2** [comment]
can you please mange it to work with google colab

- browser..cp39-win_amd64
- encryption.cp39-win_amd64

**Comment by ghis21** [comment]
Had the same problem while running on Jupyter. 
ModuleNotFoundError: No module named 'TiktokApi.browser'

pip install the modules inside requirements.txt. And the browser and encryption pyd files are inside the TiktokApi folder.
Did I miss out something?

**Comment by ghis21** [comment]
> Had the same problem while running on Jupyter. ModuleNotFoundError: No module named 'TiktokApi.browser'
> 
> pip install the modules inside requirements.txt. And the browser and encryption pyd files are inside the TiktokApi folder. Did I miss out something?

ok, seems like just need to remove the middle string from "browser.cp39-win_amd64.pyd" to "browser.pyd".

**Comment by lazezo2** [comment]
this module extension build for windows and will not work in other system.....

- browser..cp39-win_amd64
- encryption.cp39-win_amd64

can you please make another build for those modules to work in google colab

**Comment by demon071** [comment]
ok i will check on colab

**Comment by lazezo2** [comment]
> ok i will check on colab

any news
