### ISSUE TITLE
 'Api.getChallengeFeed': How to use this api to send next pages request?  

### ISSUE THREAD

**Issue by Refrain-WG** [demon071/Tiktok-API-Python#3]
Does this api `getChallengeFeed` support request next pages data now? I tried but I have no idea.

**Comment by demon071** [comment]
you can use maxCursor to call the next page, ``` Api.getChallengeFeed ('trending', maxCursor) ```

**Comment by Refrain-WG** [comment]
> you can use maxCursor to call the next page, `Api.getChallengeFeed ('trending', maxCursor)`

I got it. Thank you for your reply.
