### ISSUE TITLE
What does this do?

### ISSUE THREAD

**Issue by MilkCoding** [demon071/Tiktok-API-Python#32]
def get_cookies(self):
        return self.driver.get_cookies()

**Comment by demon071** [comment]
> def get_cookies(self): return self.driver.get_cookies()

returns a cookie, if you want to download the video you will need it

**Comment by MilkCoding** [comment]
> > def get_cookies(self): return self.driver.get_cookies()
> 
> returns a cookie, if you want to download the video you will need it

okie thank you! learning how to code so i get curious
