### ISSUE TITLE
What exactly does the trending.py file return? Is it the trending hashtags in my area?

### ISSUE THREAD

**Issue by amin-farah** [demon071/Tiktok-API-Python#33]

**Comment by demon071** [comment]
It depends on what region of the Internet you are using!

**Comment by amin-farah** [comment]
Ah okay, thank you! Also, are the returned videos the ones that initially appear on a new account created in that region?

**Comment by demon071** [comment]
Those are the videos that are trending in that area, there may be old videos or new videos
