### ISSUE TITLE
Feature Request 🧾

### ISSUE THREAD

**Issue by WhoAreYou-69** [demon071/Tiktok-API-Python#5]
- Hey there, The Api is great but could you make a function to get video info for example 
**vid_info = Api.getVideo_infoById('6897853325761350913')**
and it returns **Caption, num of comments, likes ,shares..etc** in an array or maybe a **json** file

- And another thing specify the path to download video
Eg : Api.DownloadVideoById('6897853325761350913', path)

That's it otherwise everything is good.

**Comment by demon071** [comment]
the update is available
