### ISSUE TITLE
No watermark url missing

### ISSUE THREAD

**Issue by EgorSigolaev** [demon071/Tiktok-API-Python#8]
Api not giving json with no watermark url. Does api provide it?

**Comment by demon071** [comment]
new api https://tiktokv.tk/ajax.php?search=https://www.tiktok.com/@j97_thanh_xuan/video/6882375186746854657&type=urlPro&max=0

**Comment by EgorSigolaev** [comment]
Thanks a lot. Does this api have limits? Can I use it for commercial
projects?


ср, 27 янв. 2021 г. в 10:30, Văn Anh <notifications@github.com>:

**Comment by EgorSigolaev** [comment]
> new api https://tiktokv.tk/ajax.php?search=https://www.tiktok.com/@j97_thanh_xuan/video/6882375186746854657&type=urlPro&max=0

Thanks a lot! 
Does it have limits? Can I use it for commercial projects?

**Comment by EgorSigolaev** [comment]
> new api https://tiktokv.tk/ajax.php?search=https://www.tiktok.com/@j97_thanh_xuan/video/6882375186746854657&type=urlPro&max=0

Api doesnt work now, wtf? xd

**Comment by demon071** [comment]
> > new api https://tiktokv.tk/ajax.php?search=https://www.tiktok.com/@j97_thanh_xuan/video/6882375186746854657&type=urlPro&max=0
> 
> Api doesnt work now, wtf? xd

You cannot call the request too many times

**Comment by EgorSigolaev** [comment]
> You cannot call the request too many times

I tried now, server is not working:( Giving error 500
